import assert from 'node:assert/strict';
import BUILTIN from '../src/builtin1192.js';
import { airCatalogFromPack } from '../src/designerData.js';
import { configureAirDataPack, AIRFRAMES, AIR_SLOT_MODULES, defaultAirDesign, normalizeAirDesign, airDesignOptions, buildAirDesign } from '../src/air.js';
const cat=airCatalogFromPack(BUILTIN);assert.equal(cat.meta.airframes,21,'only concrete 1.19.2 airframes are selectable');assert.equal(cat.meta.carrierAirframes,5);assert.equal(cat.meta.slotCategories,29);assert.equal(cat.meta.slotModules,94);assert.equal(cat.meta.engines,33);assert.equal(cat.meta.weapons,29);assert.ok(!cat.airframes.small_plane_airframe&&!cat.airframes.cv_small_plane_airframe&&!cat.airframes.medium_plane_airframe&&!cat.airframes.large_plane_airframe,'airframe archetype templates are not selectable');
assert.ok(!cat.slotModules.tank_medium_cannon,'tank armament must not leak into Air Designer');assert.ok(!cat.slotModules.lc_medium_cannon_turret,'Land Cruiser armament must not leak into Air Designer');const sourceCats=new Set(Object.values(cat.airframes).flatMap(f=>Object.values(f._equipment.moduleSlots||{}).flatMap(slot=>Array.isArray(slot.allowed_module_categories)?slot.allowed_module_categories:[slot.allowed_module_categories])));for(const [id,rec] of Object.entries(cat.slotModules))if(id!=='none')assert.ok(sourceCats.has(rec.category),`${id} is not referenced by any concrete aircraft slot category`);
configureAirDataPack(BUILTIN,1940);assert.equal(Object.keys(AIRFRAMES).length,21);assert.equal(Object.keys(AIR_SLOT_MODULES).length-1,94);
const d=defaultAirDesign('small'),frame=AIRFRAMES[d.airframe],opts=airDesignOptions(d);assert.ok(d.airframe.startsWith('small_plane_airframe_'));assert.equal(frame.carrier,false);for(const [slotId,slot] of Object.entries(frame._equipment.moduleSlots)){assert.ok(opts.slots[slotId]);if(slot.required)assert.notEqual(d.slotModules[slotId],'none',`${slotId} is required`);assert.ok(opts.slots[slotId].has(d.slotModules[slotId]),`${d.slotModules[slotId]} must be source-compatible with ${slotId}`);}
const jet=normalizeAirDesign({...d,airframe:'small_plane_airframe_5'},'small'),jetOpts=airDesignOptions(jet);assert.ok(jetOpts.slots.engine_type_slot.has('jet_engine_1x'));assert.ok(jetOpts.slots.engine_type_slot.has('rocket_engine_1'));assert.ok(!jetOpts.slots.engine_type_slot.has('engine_4_1x'),'1950 small airframe source slot excludes piston engines');
const carrier=normalizeAirDesign({...d,airframe:'cv_small_plane_airframe_3'},'small');assert.equal(AIRFRAMES[carrier.airframe].carrier,true);for(const [slotId,slot] of Object.entries(AIRFRAMES[carrier.airframe]._equipment.moduleSlots))if(slot.required)assert.notEqual(carrier.slotModules[slotId],'none');
const migrated=normalizeAirDesign({name:'Legacy Fighter',engine:'engine_3',weapons:['heavy_mg','bomb_locks','none'],defense:'self_sealing',specials:['drop_tanks','none']},'small');assert.ok(migrated.slotModules.engine_type_slot&&migrated.slotModules.engine_type_slot!=='none');assert.ok(Object.values(migrated.slotModules).some(x=>x==='heavy_mg_4x'||x==='heavy_mg_2x'));const built=buildAirDesign(migrated);assert.ok(built.buildCost>0&&built.thrust>0);assert.ok(built.roles.includes('fighter'),'role comes from source add_equipment_type metadata');assert.equal(built.source,'game-pack');assert.equal(built.missionStatCompleteness,'partial-bundle');
const casSlots={...migrated.slotModules};const casSlot=Object.keys(AIRFRAMES[migrated.airframe]._equipment.moduleSlots).find(slot=>airDesignOptions(migrated).slots[slot]?.has('bomb_locks'));if(casSlot){casSlots[casSlot]='bomb_locks';const cas=buildAirDesign(normalizeAirDesign({...migrated,slotModules:casSlots},'small'));assert.ok(cas.roles.includes('cas'),'CAS role is identified from source equipment type metadata even while mission-stat blocks remain incomplete');}
assert.equal(BUILTIN.meta.airMissionStatBlocksCertified,false);assert.equal(BUILTIN.meta.airDuplicateArchetypesCertified,false);console.log('1.19.2 Air Designer structural/source-slot invariants passed.');
