import assert from 'node:assert/strict';
import { parseClausewitz, extractEquipmentModules } from '../src/parser.js';
const parsed=parseClausewitz(`equipment_modules={ bomb={ category=cas_weapon mission_type_stats={ limit={ cas attack_logistics } add_stats={ air_ground_attack=6 } } mission_type_stats={ limit={ naval_bomber port_strike } add_stats={ naval_strike_attack=2 } } } }`);
const m=extractEquipmentModules(parsed).bomb;
assert.equal(m.missionTypeStats.length,2);
assert.deepEqual(m.missionTypeStats[0].limit,['cas','attack_logistics']);
assert.equal(m.missionTypeStats[0].add_stats.air_ground_attack,6);
assert.deepEqual(m.missionTypeStats[1].limit,['naval_bomber','port_strike']);
assert.equal(m.missionTypeStats[1].add_stats.naval_strike_attack,2);
console.log('Air repeated/multi-mission parser invariants passed.');
