import assert from 'node:assert/strict';
import pack from '../src/builtin1192.js';
import { gameDataCoverage } from '../src/gameData.js';
import { tankCatalogFromPack, airCatalogFromPack } from '../src/designerData.js';

assert.equal(pack.meta.gameVersion,'1.19.2');
assert.equal(pack.meta.bundled,true);
assert.ok(Object.keys(pack.defines.NMilitary||{}).length>300,'real NMilitary defines bundled');
assert.ok(Object.keys(pack.defines.NProduction||{}).length>50,'real NProduction defines bundled');
assert.ok(pack.subUnits.infantry);
assert.ok(pack.subUnits.helicopter_recon,'advanced helicopter support is present');
assert.ok(pack.subUnits.light_flame_tank,'canonical flame tank support is present');
assert.ok(pack.subUnits.medium_flame_tank&&pack.subUnits.heavy_flame_tank,'all vanilla flame tank support classes are present');
assert.equal(pack.subUnits.light_flame_tank.need.light_tank_flame_chassis,15,'flame tank support keeps its real chassis requirement');
assert.ok(pack.equipment.infantry_equipment_2);
assert.ok(Object.keys(pack.modules).length>=313,'full repeated-block module corpus is bundled');
assert.ok(pack.doctrines.mobile_infantry);
assert.ok(pack.doctrines.new_mobile_warfare);
assert.equal(pack.doctrines.new_mobile_warfare.raw.milestones.length,4,'anonymous milestone blocks survive parsing');
assert.ok(Object.keys(pack.combatTactics).length>=50);
assert.ok(Object.keys(pack.specialProjects).length>=40);
const requirementRelationships=Object.values(pack.requirements||{}).reduce((total,group)=>total+Object.values(group||{}).reduce((n,list)=>n+(Array.isArray(list)?list.length:0),0),0);
assert.equal(requirementRelationships,761,'all real prerequisite relationships, including restored standard tank modules, are bundled');
const coverage=gameDataCoverage(pack);
assert.ok(coverage.subUnits>=100&&coverage.equipment>=200&&coverage.technologies>=500);
const tank=tankCatalogFromPack(pack),air=airCatalogFromPack(pack);
assert.ok(tank.meta.chassis>0&&tank.meta.guns>0&&tank.meta.engines>0,'real tank chassis, guns and engines resolve into the designer catalog');
assert.ok(air.meta.airframes>0&&air.meta.engines>0&&air.meta.weapons>0,'real airframes, engines and weapons resolve into the aircraft designer catalog');
console.log('bundled HOI4 1.19.2 data tests passed');
