import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const read=path=>readFile(new URL(path,root),'utf8');
const [index,direction,runtimeGuard,mode,baseView,model,candidates,forceCandidates,search,searchView,explanations]=await Promise.all([
  read('index.html'),read('src/product-direction-runtime.js'),read('src/runtime-guard.js'),read('src/counter-analysis-ui.js'),read('src/counter-base-view.js'),read('src/counter-state-model.js'),read('src/counter-candidates.js'),read('src/counter-force-candidates.js'),read('src/counter-search.js'),read('src/counter-search-view.js'),read('src/counter-explanations.js')
]);
assert.match(index,/Counter Analysis/);
assert.match(index,/counter-analysis\.css/);
assert.match(index,/counter-results-ui\.js/);
assert.match(index,/counter-analysis-ui\.js/);
assert.match(direction,/\['dashboard','front','intel','production'\]/,'Command and the prior operational-planning routes must remain retired');
assert.match(direction,/HOI4 WAR PLANNER/,'persistent shell must use the current analysis product identity');
assert.match(direction,/Build · Compare · Improve · Stress-test/,'top-level shell must communicate the current product workflow');
assert.match(runtimeGuard,/RETIRED_PUBLIC_ROUTES=new Set\(\['dashboard','front','intel','production'\]\)/,'retired hashes must be normalized before the main SPA renders');
assert.match(runtimeGuard,/history\.replaceState\(null,'',`\$\{location\.pathname\}\$\{location\.search\}#battle`\)/,'legacy Command links must land directly in Division Lab without rendering the retired dashboard first');
assert.match(mode,/COUNTER ANALYSIS/);
assert.match(mode,/TEST THIS DIVISION →/,'Division Lab must expose a prominent one-click combat shortcut');
assert.match(mode,/COMBAT TEST →/,'Counter Analysis must expose a one-click return to combat testing');
assert.match(mode,/data-lab-panel="combat"/,'combat shortcut must activate the real Combat sub-tab');
assert.match(mode,/if\(shortcut\.textContent!==label\)shortcut\.textContent=label/,'combat shortcut updates must be idempotent under the MutationObserver');
assert.match(baseView,/id="runCounterSearch">IMPROVE ATTACKER/,'the existing attacker analysis control must remain available');
assert.match(baseView,/id="runDefenderCounterSearch">IMPROVE DEFENDER/,'Counter Analysis must expose a separate defender recommendation control');
assert.match(baseView,/detail:\{side:'attacker'/);
assert.match(baseView,/detail:\{side:'defender'/);
assert.match(model,/buildTechAdjustedData/);
assert.match(model,/applyMioEquipmentBonus/);
assert.match(model,/applyTankDesignToBattalion/);
assert.match(model,/derivedCache=new WeakMap/,'Counter Analysis must cache expensive derived force data by state');
assert.match(model,/state\.productionGoals/,'Counter snapshots must retain the saved production plan');
assert.match(model,/p:state\.production,pg:state\.productionGoals/,'production changes must invalidate stale Counter results');
assert.match(candidates,/canPlaceBattalion/);
assert.match(candidates,/side='attacker'/,'template candidate generation must be side-aware');
assert.match(candidates,/state\[side\+'Grid'\]/,'template candidate generation must read the selected side grid');
assert.match(candidates,/priorKinds/);
assert.match(candidates,/replace-support/);
assert.match(forceCandidates,/tankDesignOptions/);
assert.match(forceCandidates,/tankVariantTargets/);
assert.match(forceCandidates,/counterForceKey/);
assert.match(forceCandidates,/sideVariants/,'tank design mutations must target only the selected side');
assert.match(forceCandidates,/quickDesignScore/,'tank candidates must be cheaply pre-ranked before full division evaluation');
assert.doesNotMatch(forceCandidates,/counterDivision|effectiveAttack/,'tank candidate enumeration must not rebuild whole divisions');
assert.match(search,/buildForceDesignCandidates/);
assert.match(search,/candidate\.kind==='tank-design'/);
assert.doesNotMatch(search,/costUnpriced/);
assert.match(search,/simulateBattle/);
assert.match(search,/result\.defenderWinRate/,'defender searches must optimize the actual defender outcome rather than invert an attacker score');
assert.match(search,/counterOperationalBurden/,'search ranking must explicitly account for supply-use burden');
assert.match(search,/supplyValuePenalty/,'Best Value must price increased supply use without inventing province supply capacity');
assert.match(search,/counterProductionPlanBurden/,'search ranking must consume saved production-plan feasibility');
assert.match(search,/productionPlan\?\.searchPenalty/,'candidate exploration must account for current production-plan burden');
assert.match(search,/isMeaningfulCounterImprovement/,'recommendations must qualify on improvement rather than requiring a winning final result');
assert.match(search,/runCounterSearchResponsive/,'live Counter Analysis must expose a yielding search path');
assert.match(search,/SAFE_DEFAULTS=\{runs:50,firstStepLimit:18,beamWidth:3,secondPerSeedLimit:10,secondStepLimit:8\}/,'default live search must remain browser-bounded');
assert.match(search,/yieldControl/,'responsive search must yield control between candidate simulations');
assert.match(search,/buildCounterRecommendationGroups/,'headline recommendations must collapse duplicate category winners');
assert.match(search,/bestTested/,'search must preserve the strongest tested attempt for hopeless matchups');
assert.match(search,/bestEfforts/,'search must retain near-miss diagnostics without expanding the live search');
assert.match(search,/counterProductionPracticality/,'Counter Analysis must classify new armor-family production commitments');
assert.match(search,/SEARCH_RETOOLING_PENALTY/,'second-step exploration must account for new armor-family retooling burden');
assert.match(search,/local=ranked\.filter\(item=>!item\.practicality\?\.majorRetooling\)/,'practical headline categories must prefer local counters when meaningful options exist');
assert.match(searchView,/runCounterSearchResponsive/,'UI must use the responsive search rather than the blocking search');
assert.match(searchView,/try\{\s*const snap=counterSnapshot\(\)/,'fresh Counter snapshots must be taken inside the feature-local error boundary');
assert.match(searchView,/countersettings[\s\S]*try\{renderResults\(host,counterSnapshot\(\),lastSide\);\}/,'Counter settings refresh must contain snapshot/render failures locally');
assert.match(searchView,/ANALYZING \$\{completed\} \/ \$\{total\}/,'UI must show bounded search progress');
assert.match(searchView,/DIVISION \+ EQUIPMENT TWO-STEP SEARCH/);
assert.match(searchView,/fixed context/);
assert.doesNotMatch(searchView,/equipment-tier upgrades|transition cost not priced|excluded from Best Value/);
assert.match(searchView,/Why it works/);
assert.match(searchView,/Tradeoffs/);
assert.match(searchView,/still below 50%/,'a large improvement must be allowed to remain a losing matchup and be labeled honestly');
assert.match(searchView,/Recommendations are improvements, not promises of victory/,'UI must state that recommendations do not guarantee a win');
assert.match(searchView,/Combat width and organization are rebuilt and re-simulated/,'UI must disclose that structural stat tradeoffs feed the battle simulation');
assert.match(searchView,/do not automatically change battlefield supply satisfaction/,'UI must disclose the current supply-capacity evidence boundary');
assert.match(searchView,/No practical local \$\{sideLabel\(side\)\} improvement found/,'hopeless matchups must produce an explicit bounded-search diagnosis');
assert.match(searchView,/BEST TESTED ATTEMPT · BELOW THRESHOLD/,'hopeless matchups should expose the strongest near-miss without calling it a qualifying counter');
assert.match(searchView,/DOMINANT PICK/,'one candidate winning several objectives must render once as a dominant pick');
assert.match(searchView,/DISTINCT ALTERNATIVE/,'duplicate headline winners should make room for distinct qualifying alternatives');
assert.match(searchView,/CURRENT PLAN GAP/,'production-limited recommendations must visibly disclose saved-plan coverage');
assert.match(searchView,/SAVED TARGET REGRESSION/,'costlier equipment retunes must visibly disclose when existing saved targets fall further behind');
assert.match(searchView,/MAJOR RETOOLING/,'new armor-family recommendations must be visibly flagged');
assert.match(searchView,/Factory conversion\/retooling efficiency loss, new trade acquisition, province-level supply capacity, and campaign fuel logistics remain outside this check/,'UI must state the narrower remaining production evidence boundary');
assert.match(explanations,/Crosses the target armor threshold/);
assert.match(explanations,/Defense increases/,'defender explanations must reward defensive staying power');
assert.match(explanations,/underlying variant/);
assert.match(explanations,/Effective attack against this exact hardness profile/);
assert.match(explanations,/existing saved production targets fall/,'counter explanations must disclose production regressions caused by costlier equipment designs');
assert.match(explanations,/Major production retooling/,'counter explanations must disclose new armor production-chain commitments');
assert.doesNotMatch(index,/enemy uncertainty bands/i);
console.log('Counter Analysis UI regression checks passed.');
