import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const read=path=>readFile(new URL(path,root),'utf8');
const [index,direction,runtimeGuard,mode,model,candidates,forceCandidates,search,searchView,explanations]=await Promise.all([
  read('index.html'),read('src/product-direction-runtime.js'),read('src/runtime-guard.js'),read('src/counter-analysis-ui.js'),read('src/counter-state-model.js'),read('src/counter-candidates.js'),read('src/counter-force-candidates.js'),read('src/counter-search.js'),read('src/counter-search-view.js'),read('src/counter-explanations.js')
]);
assert.match(index,/Counter Analysis/);
assert.match(index,/counter-analysis\.css/);
assert.match(index,/counter-results-ui\.js/);
assert.match(index,/counter-analysis-ui\.js/);
assert.match(direction,/\['dashboard','front','intel','production'\]/,'Command and the prior operational-planning routes must remain retired');
assert.match(direction,/HOI4 WAR PLANNER/,'persistent shell must use the current analysis product identity');
assert.match(direction,/Build · Compare · Improve · Stress-test/,'top-level shell must communicate the current product workflow');
assert.match(runtimeGuard,/RETIRED_PUBLIC_ROUTES=new Set\(\['dashboard','front','intel','production'\]\)/,'retired hashes must be normalized before the main SPA renders');
assert.match(runtimeGuard,/history\.replaceState\(null,'',`\$\{location\.pathname\}\$\{location\.search\}#battle`\)/,'legacy Command links must land directly in Division Lab without rendering the retired dashboard first');
assert.match(mode,/COUNTER ANALYSIS/);
assert.match(mode,/TEST THIS DIVISION →/,'Division Lab must expose a prominent one-click combat shortcut');
assert.match(mode,/COMBAT TEST →/,'Counter Analysis must expose a one-click return to combat testing');
assert.match(mode,/data-lab-panel="combat"/,'combat shortcut must activate the real Combat sub-tab');
assert.match(model,/buildTechAdjustedData/);
assert.match(model,/applyMioEquipmentBonus/);
assert.match(model,/applyTankDesignToBattalion/);
assert.match(model,/derivedCache=new WeakMap/,'Counter Analysis must cache expensive derived force data by state');
assert.match(candidates,/canPlaceBattalion/);
assert.match(candidates,/priorKinds/);
assert.match(candidates,/replace-support/);
assert.match(forceCandidates,/tankDesignOptions/);
assert.match(forceCandidates,/tankVariantTargets/);
assert.match(forceCandidates,/counterForceKey/);
assert.match(forceCandidates,/quickDesignScore/,'tank candidates must be cheaply pre-ranked before full division evaluation');
assert.doesNotMatch(forceCandidates,/counterDivision|effectiveAttack/,'tank candidate enumeration must not rebuild whole divisions');
assert.match(search,/buildForceDesignCandidates/);
assert.match(search,/candidate\.kind==='tank-design'/);
assert.doesNotMatch(search,/costUnpriced/);
assert.match(search,/simulateBattle/);
assert.match(search,/runCounterSearchResponsive/,'live Counter Analysis must expose a yielding search path');
assert.match(search,/SAFE_DEFAULTS=\{runs:50,firstStepLimit:18,beamWidth:3,secondPerSeedLimit:10,secondStepLimit:8\}/,'default live search must remain browser-bounded');
assert.match(search,/yieldControl/,'responsive search must yield control between candidate simulations');
assert.match(searchView,/runCounterSearchResponsive/,'UI must use the responsive search rather than the blocking search');
assert.match(searchView,/ANALYZING \$\{completed\} \/ \$\{total\}/,'UI must show bounded search progress');
assert.match(searchView,/DIVISION \+ EQUIPMENT TWO-STEP SEARCH/);
assert.match(searchView,/fixed context/);
assert.doesNotMatch(searchView,/equipment-tier upgrades|transition cost not priced|excluded from Best Value/);
assert.match(searchView,/Why it works/);
assert.match(searchView,/Tradeoffs/);
assert.match(explanations,/Crosses the target armor threshold/);
assert.match(explanations,/underlying variant/);
assert.match(explanations,/Effective attack against this exact hardness profile/);
assert.doesNotMatch(index,/enemy uncertainty bands/i);
console.log('Counter Analysis UI regression checks passed.');
