-- HOI4 War Planner Oracle O19 combined normal-damage coherence probe.
NDefines.NMilitary.BASE_CHANCE_TO_AVOID_HIT = 90
NDefines.NMilitary.CHANCE_TO_AVOID_HIT_AT_NO_DEF = 100
NDefines.NMilitary.LAND_COMBAT_ORG_DAMAGE_MODIFIER = 0.053
NDefines.NMilitary.LAND_COMBAT_ORG_DICE_SIZE = 4
NDefines.NMilitary.LAND_COMBAT_ORG_ARMOR_ON_SOFT_DICE_SIZE = 6
NDefines.NMilitary.LAND_COMBAT_STR_DAMAGE_MODIFIER = 0.060
NDefines.NMilitary.LAND_COMBAT_STR_DICE_SIZE = 2
NDefines.NMilitary.LAND_COMBAT_STR_ARMOR_ON_SOFT_DICE_SIZE = 2
NDefines.NMilitary.BASE_NIGHT_ATTACK_PENALTY = 0
