-- Oracle O17v2 strength-scale confirmation.
NDefines.NMilitary.BASE_CHANCE_TO_AVOID_HIT = 0
NDefines.NMilitary.CHANCE_TO_AVOID_HIT_AT_NO_DEF = 0
NDefines.NMilitary.LAND_COMBAT_ORG_DAMAGE_MODIFIER = 0
NDefines.NMilitary.LAND_COMBAT_ORG_DICE_SIZE = 1
NDefines.NMilitary.LAND_COMBAT_ORG_ARMOR_ON_SOFT_DICE_SIZE = 1
NDefines.NMilitary.LAND_COMBAT_STR_DAMAGE_MODIFIER = 0.060
NDefines.NMilitary.LAND_COMBAT_STR_DICE_SIZE = 1
NDefines.NMilitary.LAND_COMBAT_STR_ARMOR_ON_SOFT_DICE_SIZE = 1
NDefines.NMilitary.BASE_NIGHT_ATTACK_PENALTY = 0
