export function clamp(n,a,b){return Math.max(a,Math.min(b,n));}
export function avgEfficiency(start,gain,days,max=100){const s=clamp(Number(start)||0,0,100),e=clamp(s+(Number(gain)||0)*(Number(days)||0),s,Number(max)||100);return ((s+e)/2)/100;}
export function productionPerDay(line,scenario){const eff=avgEfficiency(scenario.efficiency,scenario.efficiencyGain,scenario.days,scenario.maxEfficiency);const bonus=1+(Number(scenario.outputBonus)||0)/100;return Math.max(0,line.factories||0)*Math.max(0,line.output||0)*eff*bonus*Math.max(0,scenario.resourceFactor??1);}
export function projectLine(line,scenario){const need=Math.max(0,(line.target||0)-(line.stock||0));const daily=productionPerDay(line,scenario);const produced=daily*Math.max(0,scenario.days||0);return {...line,daily,produced,need,ending:(line.stock||0)+produced,shortage:Math.max(0,need-produced),completionDays:daily>0?need/daily:Infinity};}
export function optimize(lines,scenario){let remaining=Math.max(0,Math.floor(scenario.factories||0));const work=lines.map(x=>({...x,factories:0}));for(let step=0;step<remaining;step++){let best=-1,bestGain=0;for(let i=0;i<work.length;i++){const before=projectLine(work[i],scenario).shortage*(work[i].priority||1);work[i].factories++;const after=projectLine(work[i],scenario).shortage*(work[i].priority||1);work[i].factories--;const gain=before-after;if(gain>bestGain){bestGain=gain;best=i;}}if(best<0)break;work[best].factories++;}return evaluate(work,scenario);}
export function evaluate(lines,scenario){const projected=lines.map(l=>projectLine(l,scenario));const resources={};projected.forEach((p,i)=>{for(const [r,q] of Object.entries(lines[i].resources||{}))resources[r]=(resources[r]||0)+p.produced*q;});const shortage=projected.reduce((a,x)=>a+x.shortage*(x.priority||1),0);return {lines:projected,shortage,used:lines.reduce((a,x)=>a+(x.factories||0),0),resources};}
export function buildDemand(templates,selected){const demand={};for(const s of selected||[]){const t=templates[s.template];if(!t)continue;for(const [e,q] of Object.entries(t.equipment||{}))demand[e]=(demand[e]||0)+q*Math.max(0,+s.count||0);}return demand;}
export function mergeGoals(goals,demand){const map=new Map((goals||[]).map(g=>[g.type,{...g}]));for(const [type,q] of Object.entries(demand||{})){const g=map.get(type)||{type,stock:0,target:0,factories:0,priority:1};g.target=Math.max(g.target||0,(g.stock||0)+q);map.set(type,g);}return [...map.values()];}
let supportsData={};
export function setSupportsData(data){supportsData=data||{};}
export function calcDivision(side,battalions,supports){const r={width:0,manpower:0,org:0,hp:0,supply:0,soft:0,hard:0,def:0,breakthrough:0,hardness:0,armor:0,piercing:0,need:{},battalions:0};let count=0;for(const x of side||[]){const u=battalions[x.type];const n=Math.max(0,+x.count||0);if(!u||!n)continue;count+=n;r.battalions+=n;r.width+=u.width*n;r.manpower+=u.manpower*n;r.org+=u.org*n;r.hp+=u.hp*n;r.supply+=u.supply*n;r.soft+=u.soft*n;r.hard+=u.hard*n;r.def+=u.def*n;r.breakthrough+=u.breakthrough*n;r.hardness+=u.hardness*n;r.armor=Math.max(r.armor,u.armor||0);r.piercing=Math.max(r.piercing,u.piercing||0);for(const [k,v] of Object.entries(u.need||{}))r.need[k]=(r.need[k]||0)+v*n;}for(const k of supports||[]){const u=supportsData[k];if(!u)continue;r.supply+=u.supply||0;r.soft+=u.soft||0;r.hard+=u.hard||0;r.def+=u.def||0;r.breakthrough+=u.breakthrough||0;r.armor=Math.max(r.armor,u.armor||0);r.piercing=Math.max(r.piercing,u.piercing||0);for(const [q,v] of Object.entries(u.need||{}))r.need[q]=(r.need[q]||0)+v;}r.org=count?Math.round(r.org/count):0;r.hardness=count?r.hardness/count:0;return r;}
export function terrainPenalty(side,battalions,terrainKey,terrainData){const t=terrainData[terrainKey]||{};const n=(side||[]).reduce((s,x)=>s+(+x.count||0),0);let p=t.attack||0;for(const x of side||[])p+=(battalions[x.type]?.terrain?.[terrainKey]||0)*(+x.count||0)/Math.max(1,n);return clamp(p,-.8,.9);}
function widthFactor(width,available){if(width<=available)return 1;return clamp(available/width,.33,1);}
function hitRate(attack,defense){if(attack<=0)return .15;const defended=clamp(defense/Math.max(1,attack),0,1);return clamp(.9-.45*defended,.25,.9);}
function armorEffect(attacker,defender){if((defender.armor||0)<=0)return {attack:1,damage:1,pierced:true};if((attacker.piercing||0)>=defender.armor)return {attack:1,damage:1,pierced:true};return {attack:.65,damage:.65,pierced:false};}
export function simulateOnce(a,d,opts){const t=opts.terrainData[opts.terrain]||{};const directions=Math.max(0,+opts.directions||0);const available=Math.max(1,(t.width||80)+directions*40);const overA=Math.max(0,a.width/available-1),overD=Math.max(0,d.width/available-1);const aWidth=widthFactor(a.width,available)*(overA?clamp(1-2*overA,.33,1):1);const dWidth=widthFactor(d.width,available)*(overD?clamp(1-2*overD,.33,1):1);const aTerrain=1-terrainPenalty(opts.attacker,opts.battalions,opts.terrain,opts.terrainData);const dTerrain=1-terrainPenalty(opts.defender,opts.battalions,opts.terrain,opts.terrainData);const asup=clamp(opts.asupply??1,0,1),dsup=clamp(opts.dsup??1,0,1),air=clamp(opts.air||0,-1,1);let aSoft=(a.soft*(1-a.hardness)+a.hard*a.hardness)*aTerrain*asup*aWidth*(1+air*.35);let dSoft=(d.soft*(1-d.hardness)+d.hard*d.hardness)*dTerrain*dsup*dWidth;const aDef=a.def*(1+(t.def||0))*asup*(1+(opts.entrench||0)*.02);const dDef=d.def*(1+(t.def||0))*dsup*(1+(opts.entrench||0)*.02);const armor=armorEffect(a,d);aSoft*=armor.attack;const fort=clamp(1-(opts.fort||0)*.15,.1,1);aSoft*=fort;let ao=Math.max(1,a.org),do_=Math.max(1,d.org),as=Math.max(1,a.hp),ds=Math.max(1,d.hp),hours=0,aCas=0,dCas=0;const aHit=hitRate(aSoft,dDef),dHit=hitRate(dSoft,aDef);while(ao>0&&do_>0&&as>0&&ds>0&&hours<168){const noiseA=1+(Math.random()-.5)*.18,noiseD=1+(Math.random()-.5)*.18;const dOrgDmg=Math.max(.05,aSoft*aHit*.035*noiseA),aOrgDmg=Math.max(.05,dSoft*dHit*.035*noiseD);const dStrDmg=Math.max(.03,aSoft*aHit*.014*noiseA),aStrDmg=Math.max(.03,dSoft*dHit*.014*noiseD);do_-=dOrgDmg;ao-=aOrgDmg;ds-=dStrDmg;as-=aStrDmg;dCas+=dStrDmg;aCas+=aStrDmg;hours++;}return {attackerWin:do_<=0||ds<=0,hours,aOrg:Math.max(0,ao),dOrg:Math.max(0,do_),aStr:Math.max(0,as),dStr:Math.max(0,ds),attackerCasualtyRate:clamp(aCas/Math.max(1,a.hp),0,1),defenderCasualtyRate:clamp(dCas/Math.max(1,d.hp),0,1),pierced:armor.pierced,width:available};}
export function simulateBattle(a,d,opts,runs=1000){const n=Math.max(1,Math.floor(runs));let wins=0,hours=0,ao=0,do_=0,ac=0,dc=0,pierced=0;for(let i=0;i<n;i++){const r=simulateOnce(a,d,opts);wins+=r.attackerWin?1:0;hours+=r.hours;ao+=r.aOrg;do_+=r.dOrg;ac+=r.attackerCasualtyRate;dc+=r.defenderCasualtyRate;pierced+=r.pierced?1:0;}return {winRate:wins/n*100,avgHours:hours/n,attOrg:ao/n,defOrg:do_/n,attackerCasualtyRate:ac/n*100,defenderCasualtyRate:dc/n*100,piercingRate:pierced/n*100};}
export function compareTerrains(a,d,opts,runs=300){return Object.keys(opts.terrainData).map(key=>({terrain:key,results:simulateBattle(a,d,{...opts,terrain:key},runs)}));}
export function readinessScore(goals,production,divisionReadiness=0){const total=(goals||[]).reduce((s,g)=>s+Math.max(0,(g.target||0)-(g.stock||0))*(g.priority||1),0);const shortage=production?.shortage||0;const equipment=total<=0?100:clamp((1-shortage/Math.max(1,total))*100,0,100);return Math.round(equipment*.7+divisionReadiness*.3);}
export function battleReadiness(attacker,defender,opts){const a=calcDivision(attacker,opts.battalions,opts.supports||[]);const d=calcDivision(defender,opts.battalions,opts.defenderSupports||[]);const sim=simulateBattle(a,d,opts,Math.min(300,opts.runs||300));return {score:Math.round(sim.winRate),attacker:a,defender:d,simulation:sim};}
