export function clamp(n,a,b){return Math.max(a,Math.min(b,n));}
export function avgEfficiency(start,gain,days,max=100){const e=Math.min(max,start+gain*days);return ((start+e)/2)/100;}
export function productionPerDay(line,scenario){const eff=avgEfficiency(scenario.efficiency,scenario.efficiencyGain,scenario.days,scenario.maxEfficiency);const bonus=1+(scenario.outputBonus||0)/100;return line.factories*line.output*eff*bonus*(scenario.resourceFactor??1);}
export function projectLine(line,scenario){const need=Math.max(0,line.target-line.stock);const daily=productionPerDay(line,scenario);const produced=daily*scenario.days;return {...line,daily,produced,need,ending:line.stock+produced,shortage:Math.max(0,need-produced),completionDays:daily>0?need/daily:Infinity};}
export function optimize(lines,scenario){let remaining=Math.max(0,Math.floor(scenario.factories));const work=lines.map(x=>({...x,factories:0}));for(let step=0;step<remaining;step++){let best=-1,bestGain=-Infinity;for(let i=0;i<work.length;i++){const before=projectLine(work[i],scenario).shortage*(work[i].priority||1);work[i].factories++;const after=projectLine(work[i],scenario).shortage*(work[i].priority||1);work[i].factories--;const gain=before-after;if(gain>bestGain){bestGain=gain;best=i;}}if(best<0||bestGain<=0)break;work[best].factories++;}return evaluate(work,scenario);}
export function evaluate(lines,scenario){const projected=lines.map(l=>projectLine(l,scenario));const resources={};projected.forEach((p,i)=>{for(const [r,q] of Object.entries(lines[i].resources||{}))resources[r]=(resources[r]||0)+p.produced*q;});const shortage=projected.reduce((a,x)=>a+x.shortage*(x.priority||1),0);return {lines:projected,shortage,used:lines.reduce((a,x)=>a+x.factories,0),resources};}
export function buildDemand(templates,selected){const demand={};for(const s of selected){const t=templates[s.template];if(!t)continue;for(const [e,q] of Object.entries(t.equipment))demand[e]=(demand[e]||0)+q*s.count;}return demand;}
export function mergeGoals(goals,demand){const map=new Map(goals.map(g=>[g.type,{...g}]));for(const [type,q] of Object.entries(demand)){const g=map.get(type)||{type,stock:0,target:0,factories:0,priority:1};g.target=Math.max(g.target,g.stock+q);map.set(type,g);}return [...map.values()];}

export function calcDivision(side,battalions,supports){const r={width:0,manpower:0,org:0,hp:0,supply:0,soft:0,hard:0,def:0,breakthrough:0,hardness:0,need:{}};let count=0;for(const x of side){const u=battalions[x.type];const n=+x.count||0;if(!u)continue;count+=n;r.width+=u.width*n;r.manpower+=u.manpower*n;r.org+=u.org*n;r.hp+=u.hp*n;r.supply+=u.supply*n;r.soft+=u.soft*n;r.hard+=u.hard*n;r.def+=u.def*n;r.breakthrough+=u.breakthrough*n;r.hardness+=u.hardness*n;for(const [k,v] of Object.entries(u.need))r.need[k]=(r.need[k]||0)+v*n;}for(const k of supports){const u=supportsData[k];if(!u)continue;r.supply+=u.supply;r.soft+=u.soft;r.hard+=u.hard;r.def+=u.def;r.breakthrough+=u.breakthrough;for(const [q,v] of Object.entries(u.need))r.need[q]=(r.need[q]||0)+v;}r.org=count?Math.round(r.org/count):0;r.hardness=count?r.hardness/count:0;return r;}
let supportsData={};
export function setSupportsData(data){supportsData=data;}
export function terrainPenalty(side,battalions,terrainKey,terrainData){const n=side.reduce((s,x)=>s+(+x.count||0),0);let p=terrainData[terrainKey].attack;for(const x of side)p+=(battalions[x.type]?.terrain?.[terrainKey]||0)*(+x.count||0)/Math.max(1,n);return Math.min(.9,Math.max(-.8,p));}
export function simulateOnce(a,d,opts){const t=opts.terrainData[opts.terrain],directions=opts.directions;let ao=a.org,do_=d.org,as=a.hp,ds=d.hp;const asup=opts.asupply,dsup=opts.dsup,air=opts.air;const aw=Math.max(1,t.width+directions*40);const overA=Math.max(0,a.width/aw-1),overD=Math.max(0,d.width/aw-1);let aAtk=a.soft*(1-terrainPenalty(opts.attacker,opts.battalions,opts.terrain,opts.terrainData))*asup*(1+air)*Math.max(.67,1-2*overA);let dAtk=d.soft*(1-terrainPenalty(opts.defender,opts.battalions,opts.terrain,opts.terrainData))*dsup*Math.max(.67,1-2*overD);let aDef=a.def*(1+t.def)*asup;let dDef=d.def*(1+t.def)*dsup;dDef*=1+opts.entrench*.02;aAtk*=Math.max(0,1-opts.fort*.15);let hours=0;while(ao>0&&do_>0&&as>0&&ds>0&&hours<240){const ah=aAtk*(aAtk>aDef?1:.5)*(1+(Math.random()-.5)*.35);const dh=dAtk*(dAtk>dDef?1:.5)*(1+(Math.random()-.5)*.35);do_-=Math.max(.05,ah*.05);ao-=Math.max(.02,ah*.018);ds-=Math.max(.05,dh*.05);as-=Math.max(.02,dh*.018);hours++;}return {attackerWin:do_<=0||ds<=0,hours,aOrg:Math.max(0,ao),dOrg:Math.max(0,do_),aStr:Math.max(0,as),dStr:Math.max(0,ds)};}
export function simulateBattle(a,d,opts,runs){let wins=0,hours=0,ao=0,do_=0;for(let i=0;i<runs;i++){const r=simulateOnce(a,d,opts);wins+=r.attackerWin?1:0;hours+=r.hours;ao+=r.aOrg;do_+=r.dOrg;}return {winRate:wins/runs*100,avgHours:hours/runs,attOrg:ao/runs,defOrg:do_/runs};}
export function compareTerrains(a,d,opts,runs=300){return Object.keys(opts.terrainData).map(key=>({...opts,terrain:key})).map(o=>({terrain:o.terrain,results:simulateBattle(a,d,o,runs)}));}