export function clamp(n,a,b){return Math.max(a,Math.min(b,n));}
export function avgEfficiency(start,gain,days,max=100){const s=clamp(Number(start)||0,0,100),e=clamp(s+(Number(gain)||0)*(Number(days)||0),s,Number(max)||100);return ((s+e)/2)/100;}
export function productionPerDay(line,scenario){const eff=avgEfficiency(scenario.efficiency,scenario.efficiencyGain,scenario.days,scenario.maxEfficiency);const bonus=1+(Number(scenario.outputBonus)||0)/100;return Math.max(0,line.factories||0)*Math.max(0,line.output||0)*eff*bonus*Math.max(0,scenario.resourceFactor??1);}
export function projectLine(line,scenario){const need=Math.max(0,(line.target||0)-(line.stock||0));const daily=productionPerDay(line,scenario);const produced=daily*Math.max(0,scenario.days||0);return {...line,daily,produced,need,ending:(line.stock||0)+produced,shortage:Math.max(0,need-produced),completionDays:daily>0?need/daily:Infinity};}
export function optimize(lines,scenario){let remaining=Math.max(0,Math.floor(scenario.factories||0));const work=lines.map(x=>({...x,factories:0}));for(let step=0;step<remaining;step++){let best=-1,bestGain=0;for(let i=0;i<work.length;i++){const before=projectLine(work[i],scenario).shortage*(work[i].priority||1);work[i].factories++;const after=projectLine(work[i],scenario).shortage*(work[i].priority||1);work[i].factories--;const gain=before-after;if(gain>bestGain){bestGain=gain;best=i;}}if(best<0)break;work[best].factories++;}return evaluate(work,scenario);}
export function evaluate(lines,scenario){const projected=lines.map(l=>projectLine(l,scenario));const resources={};projected.forEach((p,i)=>{for(const [r,q] of Object.entries(lines[i].resources||{}))resources[r]=(resources[r]||0)+p.produced*q;});const shortage=projected.reduce((a,x)=>a+x.shortage*(x.priority||1),0);return {lines:projected,shortage,used:lines.reduce((a,x)=>a+(x.factories||0),0),resources};}
export function buildDemand(templates,selected){const demand={};for(const s of selected||[]){const t=templates[s.template];if(!t)continue;for(const [e,q] of Object.entries(t.equipment||{}))demand[e]=(demand[e]||0)+q*Math.max(0,+s.count||0);}return demand;}
export function mergeGoals(goals,demand){const map=new Map((goals||[]).map(g=>[g.type,{...g}]));for(const [type,q] of Object.entries(demand||{})){const g=map.get(type)||{type,stock:0,target:0,factories:0,priority:1};g.target=Math.max(g.target||0,(g.stock||0)+q);map.set(type,g);}return [...map.values()];}
let supportsData={};
export function setSupportsData(data){supportsData=data||{};}
export function calcDivision(side,battalions,supports){const r={width:0,manpower:0,org:0,hp:0,supply:0,soft:0,hard:0,def:0,breakthrough:0,hardness:0,armor:0,piercing:0,need:{},battalions:0};let count=0;for(const x of side||[]){const u=battalions[x.type];const n=Math.max(0,+x.count||0);if(!u||!n)continue;count+=n;r.battalions+=n;r.width+=u.width*n;r.manpower+=u.manpower*n;r.org+=u.org*n;r.hp+=u.hp*n;r.supply+=u.supply*n;r.soft+=u.soft*n;r.hard+=u.hard*n;r.def+=u.def*n;r.breakthrough+=u.breakthrough*n;r.hardness+=u.hardness*n;r.armor=Math.max(r.armor,u.armor||0);r.piercing=Math.max(r.piercing,u.piercing||0);for(const [k,v] of Object.entries(u.need||{}))r.need[k]=(r.need[k]||0)+v*n;}for(const k of supports||[]){const u=supportsData[k];if(!u)continue;r.supply+=u.supply||0;r.soft+=u.soft||0;r.hard+=u.hard||0;r.def+=u.def||0;r.breakthrough+=u.breakthrough||0;r.armor=Math.max(r.armor,u.armor||0);r.piercing=Math.max(r.piercing,u.piercing||0);for(const [q,v] of Object.entries(u.need||{}))r.need[q]=(r.need[q]||0)+v;}r.org=count?Math.round(r.org/count):0;r.hardness=count?r.hardness/count:0;return r;}
export function terrainPenalty(side,battalions,terrainKey,terrainData){const t=terrainData[terrainKey]||{};const n=(side||[]).reduce((s,x)=>s+(+x.count||0),0);let p=t.attack||0;for(const x of side||[])p+=(battalions[x.type]?.terrain?.[terrainKey]||0)*(+x.count||0)/Math.max(1,n);return clamp(p,-.8,.9);}
function widthFactor(width,available){if(width<=available)return 1;return clamp(available/Math.max(1,width),.33,1);}
function attackVsDefense(attack,defense){const a=Math.max(0,attack),d=Math.max(0,defense);if(a<=0)return 0;const blocked=Math.min(a,d);const unblocked=Math.max(0,a-d);return blocked*.10+unblocked*.40;}
function armorDamageMultiplier(attackerPiercing,defenderArmor){const p=Math.max(0,attackerPiercing||0),a=Math.max(0,defenderArmor||0);if(a<=0)return 1;if(p>=a)return 1;if(p<=a*.75)return .5;return .5+.5*((p-a*.75)/(a*.25));}
function armorAttackMultiplier(attackerPiercing,defenderArmor){const p=Math.max(0,attackerPiercing||0),a=Math.max(0,defenderArmor||0);if(a<=0||p>=a)return 1;return .9+.1*(p/Math.max(a,1));}
function sideTerrainModifier(side,battalions,terrainKey,terrainData){const t=terrainData[terrainKey]||{};const n=(side||[]).reduce((s,x)=>s+(+x.count||0),0);let m=1+(t.attack||0);for(const x of side||[]){const v=battalions[x.type]?.terrain?.[terrainKey]||0;m+=v*(+x.count||0)/Math.max(1,n);}return clamp(m,.2,1.25);}
function sideTerrainDefenseModifier(terrainData,terrainKey){return clamp(1+(terrainData[terrainKey]?.def||0),.25,1.5);}
function supplyAttackModifier(supply){return clamp(.25+.75*clamp(Number(supply??1),0,1),.25,1);}
function overWidthFactor(width,available){if(width<=available)return 1;return clamp(1-(width-available)/Math.max(1,available),.33,1);}
export function simulateOnce(a,d,opts){const t=opts.terrainData[opts.terrain]||{};const directions=Math.max(0,+opts.directions||0);const available=Math.max(1,(t.width||90)+directions*40);const aWidth=widthFactor(a.width,available)*overWidthFactor(a.width,available);const dWidth=widthFactor(d.width,available)*overWidthFactor(d.width,available);const aTerrain=sideTerrainModifier(opts.attacker,opts.battalions,opts.terrain,opts.terrainData);const dTerrain=sideTerrainModifier(opts.defender,opts.battalions,opts.terrain,opts.terrainData);const terrainDef=sideTerrainDefenseModifier(opts.terrainData,opts.terrain);const asup=supplyAttackModifier(opts.asupply??1),dsup=supplyAttackModifier(opts.dsup??1),air=clamp(opts.air||0,-1,1);const entrench=1+Math.max(0,Number(opts.entrench)||0)*.02;const fort=clamp(1-Math.max(0,Number(opts.fort)||0)*.15,.1,1);let aAttack=((a.soft*(1-a.hardness)+a.hard*a.hardness)*aTerrain*aWidth*asup*(1+air*.35))*armorAttackMultiplier(a.piercing,d.armor)*fort;let dAttack=((d.soft*(1-d.hardness)+d.hard*d.hardness)*dTerrain*dWidth*dsup);const aDefense=Math.max(0,a.def*terrainDef*asup);const aBreakthrough=Math.max(0,a.breakthrough*terrainDef*asup*entrench);const dDefense=Math.max(0,d.def*terrainDef*dsup*entrench);const dBreakthrough=Math.max(0,d.breakthrough*terrainDef*dsup);const aHits=attackVsDefense(dAttack,aBreakthrough);const dHits=attackVsDefense(aAttack,dDefense);const aArmor=armorDamageMultiplier(d.piercing,a.armor);const dArmor=armorDamageMultiplier(a.piercing,d.armor);let ao=Math.max(1,a.org),do_=Math.max(1,d.org),as=Math.max(1,a.hp),ds=Math.max(1,d.hp),hours=0,aCas=0,dCas=0;const orgDamagePerHit=.0125,strengthDamagePerHit=.005;while(ao>0&&do_>0&&as>0&&ds>0&&hours<168){const noiseA=1+(Math.random()-.5)*.12,noiseD=1+(Math.random()-.5)*.12;const dOrgDmg=Math.max(.001,aHits*orgDamagePerHit*noiseA*dArmor);const aOrgDmg=Math.max(.001,dHits*orgDamagePerHit*noiseD*aArmor);const dStrDmg=Math.max(.0005,aHits*strengthDamagePerHit*noiseA*dArmor);const aStrDmg=Math.max(.0005,dHits*strengthDamagePerHit*noiseD*aArmor);do_-=dOrgDmg;ao-=aOrgDmg;ds-=dStrDmg;as-=aStrDmg;dCas+=dStrDmg;aCas+=aStrDmg;hours++;}return {attackerWin:do_<=0||ds<=0,hours,aOrg:Math.max(0,ao),dOrg:Math.max(0,do_),aStr:Math.max(0,as),dStr:Math.max(0,ds),attackerCasualtyRate:clamp(aCas/Math.max(1,a.hp),0,1),defenderCasualtyRate:clamp(dCas/Math.max(1,d.hp),0,1),pierced:d.piercing>=a.armor,piercingSuccess:d.piercing>=a.armor,width:available,attackerHitsPerHour:aHits,defenderHitsPerHour:dHits};}
export function simulateBattle(a,d,opts,runs=1000){const n=Math.max(1,Math.floor(runs));let wins=0,hours=0,ao=0,do_=0,ac=0,dc=0,pierced=0,ah=0,dh=0;for(let i=0;i<n;i++){const r=simulateOnce(a,d,opts);wins+=r.attackerWin?1:0;hours+=r.hours;ao+=r.aOrg;do_+=r.dOrg;ac+=r.attackerCasualtyRate;dc+=r.defenderCasualtyRate;pierced+=r.pierced?1:0;ah+=r.attackerHitsPerHour;dh+=r.defenderHitsPerHour;}return {winRate:wins/n*100,avgHours:hours/n,attOrg:ao/n,defOrg:do_/n,attackerCasualtyRate:ac/n*100,defenderCasualtyRate:dc/n*100,piercingRate:pierced/n*100,attackerHitsPerHour:ah/n,defenderHitsPerHour:dh/n};}
export function compareTerrains(a,d,opts,runs=300){return Object.keys(opts.terrainData).map(key=>({terrain:key,results:simulateBattle(a,d,{...opts,terrain:key},runs)}));}
export function readinessScore(goals,production,divisionReadiness=0){const total=(goals||[]).reduce((s,g)=>s+Math.max(0,(g.target||0)-(g.stock||0))*(g.priority||1),0);const shortage=production?.shortage||0;const equipment=total<=0?100:clamp((1-shortage/Math.max(1,total))*100,0,100);return Math.round(equipment*.7+divisionReadiness*.3);}
export function battleReadiness(attacker,defender,opts){const a=calcDivision(attacker,opts.battalions,opts.supports||[]);const d=calcDivision(defender,opts.battalions,opts.defenderSupports||[]);const sim=simulateBattle(a,d,opts,Math.min(300,opts.runs||300));return {score:Math.round(sim.winRate),attacker:a,defender:d,simulation:sim};}
